# syntax = docker/dockerfile:1

ARG RUBY_VERSION=4.0.5
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential libpq-dev git pkg-config libyaml-dev \
    curl libvips postgresql-client libyaml-0-2 nodejs npm

ENV RAILS_ENV="development" \
    BUNDLE_DEPLOYMENT="" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT=""

COPY .ruby-version Gemfile Gemfile.lock ./
RUN bundle config set --local frozen false && \
    bundle lock --add-platform x86_64-linux && \
    bundle install

COPY . .

RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp

USER 1000:1000

EXPOSE 3000 3035

CMD ["bin/dev"]
